### ISSUE TITLE
Are there any newer / more active projects, or is this unmantained just because it's complete?

### ISSUE THREAD

**Issue by illtellyoulater** [migrs/rack-server-pages#1]
This is exactly what I needed for serving a few small HTML files with some ruby in them. But it seems that the repo has not been touched in 3 years, so I was wondering if there are newer ways to do this (which I couldn't find) or basically this is it and it has not been touched because it's feature complete? :) Thank you.

**Comment by dblock** [comment]
I had the same question and wanted to try and take this project over, contribute/fix. Didn't get a response from @migrs, maybe he's reading this? I want to start with #5.

**Comment by dblock** [comment]
I made pull requests and tried to contact @migrs by various ways. For now didn't get a reply, but I'll keep trying before forking. In the meantime I'll collect all the fixes in https://github.com/dblock/rack-server-pages/tree/next. Feel free to give it a try.

**Comment by migrs** [comment]
@jjgh @dblock I'm sorry I have left this project for a long time. I just merged @dblock 's PR(#5) and I will release new version asap.

**Comment by dblock** [comment]
@migrs If I can help with the maintenance I would be more than happy to! Feel free to add me to the repo/gem owners - I can make a release too.

**Comment by dblock** [comment]
@migrs and I have connected and the project is now maintained. I've added support for Rack 3.0 in #16 and will make a release soon.
