### ISSUE TITLE
In the browser, adding .erb to the URL path for an existing path, makes the server send the .erb file rather than its output

### ISSUE THREAD

**Issue by illtellyoulater** [migrs/rack-server-pages#2]
I am not sure if this is something that has to be addressed / configured in rack-server-pages, or it's just something that I should deal with the nginx conf?

**Comment by dblock** [comment]
I couldn't reproduce this on the current version of rack-server-pages.

![Screenshot 2024-10-19 at 9 54 32 AM](https://github.com/user-attachments/assets/62fdb135-954a-45b5-95ae-7696c8152a22)

Added a test in #20.
